# Generated by Django 2.1.5 on 2019-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecwc_sessions', '0002_choice_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice_model',
            name='session_choice',
        ),
        migrations.AddField(
            model_name='choice_model',
            name='session_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
